config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resource :session
  resources :progress, only: [ :index ]
  resources :faction, only: [ :index ]
  resources :ranked_war, only: [ :index ]
  resources :hall_of_famers, only: [ :index ]
  resources :welcome, only: [ :index ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_footer.html.erb
<footer>
  <a href="https://www.torn.com/profiles.php?XID=2728237" target="_blank" rel="noopener">
    <p>&copy; <%= Time.current.year %> Bram [2728237]</p>
  </a>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= render "layouts/navbar" %>
</header>

app/views/layouts/_navbar.html.erb
<nav data-controller="navbar">
  <% if authenticated? %>
    <%= link_to "TornManager", progress_index_path, class: "navbar-link navbar-title" %>
    <%= link_to "[p] My Progress", progress_index_path, class: "navbar-link" %>
    <%= link_to "[f] My Faction", faction_index_path, class: "navbar-link" %>
    <%= link_to "[r] Ranked War", ranked_war_index_path, class: "navbar-link" %>
    <%= link_to "[h] Hall of Famers", hall_of_famers_path, class: "navbar-link" %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tornmanager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Tornmanager">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="<%= asset_path('ns_favi.ico') %>" type="image/x-icon">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>